### ISSUE TITLE
Possible to download counts per gene

### ISSUE THREAD

**Issue by alneberg** [EnvGen/BARM_web_server#33]
From functional annotation site

Add annotation and taxonomy as column

**Comment by andand** [comment]
Här kommer en gene-count fil.

Kolumnen "function" är relevant då man laddar ner data från Functional
Categories. Samma typ av tabell som genereras vid en blastning skulle
antingen kunna sakna denna kolumn, eller så kanske man kan ange alla
funktioner som genen är kopplad till tex separerade med |

/Anders
